# -*- coding: utf-8 -*-
"""src_frailty_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16IMYQU0NcsVBv4t9tQm0wthGtRZ_iT68
"""

#UPLOADED FILE IN GOOGLE COLAB
from google.colab import files

uploaded = files.upload()

#IMPORTED PANDAS TO LOOK AT ___
import pandas as pd

#LOADED RAW DATA
df = pd.read_csv("raw_frailty_data.csv", encoding="latin1")

df.head()

#LOOKED OVER INFO OF THE DATA
df.info()

#LOOKED OVER ___ INFO OF THE DATA
df.describe()

#CHECKED FOR NULLS
df.isnull().sum()

#CHECKED FOR DUPLICATES
df.duplicated().sum()

#CHECKED FOR MISSING VALUES
df.dropna()

#PROOF OF NO MISSING VALUES
print("Before:", df.shape)

df = df.dropna()

print("After:", df.shape)

df.to_csv("frailty_data_clean.csv", index=False)

from google.colab import files
files.download("frailty_data_clean.csv")