# -*- coding: utf-8 -*-
"""src_clean_frailty_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16IMYQU0NcsVBv4t9tQm0wthGtRZ_iT68
"""

#UPLOADED FILE IN GOOGLE COLAB
from google.colab import files

uploaded = files.upload()

#IMPORTED PANDAS TO LOOK AT THE DATA ANALYSIS LIBRARY
import pandas as pd

#LOADED RAW DATA
df = pd.read_csv("raw_frailty_data.csv", encoding="latin1")

df.head()

#LOOKED OVER INFO OF THE DATA
df.info()

#LOOKED OVER STATISTICALLY INFO OF THE DATA
df.describe()

#DATA TYPES
df.dtypes

#COLUMN NAMES
df.columns

#CLEAN COLUMN NAMES
df.columns = df.columns.str.strip()

#REMOVE ALL WHITESPACE FROM NUMERIC COLUMNS
df["Height"] = df["Height"].astype(str).str.replace(r"\s+", "", regex=True)
df["Weight"] = df["Weight"].astype(str).str.replace(r"\s+", "", regex=True)
df["Age"] = df["Age"].astype(str).str.replace(r"\s+", "", regex=True)
df["Grip strength"] = df["Grip strength"].astype(str).str.replace(r"\s+", "", regex=True)

#COVERT OBJECT (D.TYPES) TO NUMBERIC (D.TYPES)
df["Height"] = pd.to_numeric(df["Height"])
df["Weight"] = pd.to_numeric(df["Weight"])
df["Age"] = pd.to_numeric(df["Age"])
df["Grip strength"] = pd.to_numeric(df["Grip strength"])

#VERIFIED D.TYPES WERE CONVERTED
df.dtypes

#CHECKED FOR NULLS
df.isnull().sum()

#CHECKED FOR DUPLICATES
df.duplicated().sum()

#CHECKED FOR MISSING VALUES
df.dropna()

#PROOF OF NO MISSING VALUES
print("Before:", df.shape)

df = df.dropna()

print("After:", df.shape)

df.to_csv("frailty_data_clean.csv", index=False)

from google.colab import files
files.download("frailty_data_clean.csv")